// Quote.swift
import Foundation

struct Quote {
    let text: String
    let soundscapeID: String
}

// List of quotes tagged by soundscape
let quotes = [
    Quote(text: "Big Sur is home to diverse ecosystems, including coastal forests, marine environments, and rugged cliffs, which support a rich variety of plant and animal life.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur serves as a critical habitat for endangered species like the California condor and the sea otter, making conservation efforts essential to maintaining biodiversity.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur's unique coastal geography influences local weather patterns, creating microclimates that foster distinct plant communities, such as the iconic redwood and cypress trees.", soundscapeID: "OceanWaves"),

    Quote(text: "Indigenous groups, including the Esselen and Ohlone tribes, have lived in harmony with the land of Big Sur for thousands of years, relying on its resources for sustenance and cultural practices.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur is rich in traditional ecological knowledge, with indigenous peoples utilizing sustainable practices to manage resources and maintain ecological balance.", soundscapeID: "OceanWaves"),
    
    Quote(text: "Efforts to preserve the ecological integrity of Big Sur are essential not only for wildlife but also for maintaining the cultural heritage of indigenous peoples in the region.", soundscapeID: "OceanWaves"),

    Quote(text: "The natural beauty and ecological significance of Big Sur continue to inspire conservation initiatives that honor the land and its original stewards.", soundscapeID: "OceanWaves"),
    
    
    Quote(text: "NASA has converted radio emissions from planets like Jupiter into sound waves, allowing us to hear the unique frequencies of these celestial bodies.", soundscapeID: "Electronic"),

    Quote(text: "The sounds of the solar wind, generated by charged particles from the sun, have been captured and translated into audio, providing insights into our solar system's dynamics.", soundscapeID: "Electronic"),

    Quote(text: "Using data from the Voyager spacecraft, NASA transformed the electromagnetic waves from the outer planets into sounds that mimic the eerie whistling of the cosmos.", soundscapeID: "Electronic"),

    Quote(text: "The intense radio emissions from Saturn's magnetosphere have been converted into sound waves, revealing the planet's unique sonic signature.", soundscapeID: "Electronic"),

    Quote(text: "NASA's Chandra X-ray Observatory has detected X-ray frequencies from distant cosmic sources, converting them into sounds that illustrate the violent processes occurring in space.", soundscapeID: "Electronic"),

    Quote(text: "The sounds produced by pulsars, rapidly rotating neutron stars emitting beams of radiation, have been translated into audio formats, allowing us to 'listen' to these cosmic lighthouses.", soundscapeID: "Electronic"),

    Quote(text: "By converting the frequencies from black holes into sound, NASA helps scientists understand the gravitational waves and phenomena associated with these mysterious entities.", soundscapeID: "Electronic"),

    Quote(text: "Data collected from the Mars rover includes atmospheric sounds converted from vibrations detected by instruments, giving us a glimpse of Martian wind and weather.", soundscapeID: "Electronic"),

    Quote(text: "NASA's imaging of cosmic background radiation has resulted in sound waves that capture the echoes of the Big Bang, offering a unique auditory experience of our universe's origins.", soundscapeID: "Electronic"),

    Quote(text: "The sounds of exoplanets, detected through variations in light and heat emissions, have been converted into audio formats, expanding our understanding of potential life beyond Earth.", soundscapeID: "Electronic"),
    
    Quote(text: "Xochimilco is home to a unique network of canals and floating gardens, known as 'chinampas,' which are an ancient Aztec agricultural technique that promotes biodiversity and sustainable farming practices.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco is designated as a UNESCO World Heritage Site due to its rich ecological diversity, including numerous endemic plant and animal species that thrive in its aquatic environments.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's canals are vital habitats for various bird species, making it an important birdwatching destination where visitors can hear the calls of species like the Mexican heron and the black-crowned night heron.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's ecosystem supports a variety of fish species, including the native axolotl, a critically endangered amphibian known for its regenerative abilities and distinctive sounds.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's lush vegetation and wetland habitats contribute to natural soundscapes, with the gentle rustling of reeds and the calls of frogs and insects creating a serene auditory experience.", soundscapeID: "Xochimilco"),

    Quote(text: "The floating gardens of Xochimilco serve as a natural filtration system, improving water quality in the canals and providing a habitat for aquatic life, while their blooming flowers attract pollinators like bees and butterflies.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's local farmers utilize sustainable farming practices in Xochimilco, which help maintain the ecological balance of the area while allowing for the production of organic crops like chilies, tomatoes, and herbs.", soundscapeID: "Xochimilco"),


    Quote(text: "The ecological significance of Xochimilco extends to its role in climate regulation, as its wetlands help store carbon and mitigate the effects of urban pollution in Mexico City.", soundscapeID: "Xochimilco"),

    Quote(text: "Efforts are underway to restore and preserve the Xochimilco ecosystem, aiming to enhance its biodiversity and promote sustainable tourism, allowing visitors to experience the harmonious sounds of nature while enjoying the area's rich cultural heritage.", soundscapeID: "Xochimilco"),
    
    Quote(text: "Vatnajökull Glacier is the largest glacier in Iceland and one of the largest in Europe, covering approximately 8% of the country's land area.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The glacier is a significant part of Vatnajökull National Park, which was established to protect its unique glacial landscapes and diverse ecosystems.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull is home to several active volcanoes, including Grimsvotn, which can cause dramatic glacial melting and flooding when they erupt.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The glacier is a crucial water source for Iceland, feeding numerous rivers and lakes that support both wildlife and human communities.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull Glacier's ice cap is estimated to be up to 1,000 meters thick in some areas, making it a significant contributor to sea level rise as it melts due to climate change.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The glacier's unique blue ice formations are a result of compressed snow that has turned into dense ice, creating stunning visual landscapes.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull is rich in biodiversity, supporting various flora and fauna, including Arctic foxes, reindeer, and numerous bird species during the summer months.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The surrounding region features dramatic landscapes, including glacial rivers, volcanic mountains, and geothermal areas that attract visitors from around the world.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Glacial meltwater from Vatnajökull feeds the Jökulsá á Fjöllum river, known for its unique canyons and rich ecosystem, which is vital for salmon migration.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull Glacier plays a significant role in Iceland's culture and history, featuring prominently in folklore and serving as a source of inspiration for artists and writers.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Climate change is causing Vatnajökull Glacier to retreat at an alarming rate, with estimates suggesting it could lose up to 30% of its mass by 2100 if current warming trends continue.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The increased melting of Vatnajökull contributes to rising sea levels, which poses a threat not only to coastal communities but also to ecosystems worldwide.", soundscapeID: "IcelandGlacier"),

    Quote(text: "As temperatures rise, the glacier's melting accelerates, leading to changes in local hydrology and affecting water availability for both wildlife and human populations.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The loss of Vatnajökull's ice cover is impacting the region's climate, with changes in weather patterns and increased vulnerability to natural disasters such as flooding and landslides.", soundscapeID: "IcelandGlacier"),
    // Add more quotes tagged with relevant soundscapeIDs
]

// Function to get random quotes based on soundscape ID
func getRandomQuote(for soundscapeID: String) -> String {
    let filteredQuotes = quotes.filter { $0.soundscapeID == soundscapeID }
    return filteredQuotes.randomElement()?.text ?? "Relax, breathe, and take life one step at a time."
}
