// Quote.swift
import Foundation

struct Quote {
    let text: String
    let soundscapeID: String
}

// List of quotes tagged by soundscape
let quotes = [
    Quote(text: "Big Sur is home to diverse ecosystems, including coastal forests, marine environments, and rugged cliffs, which support a rich variety of plant and animal life.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur serves as a critical habitat for endangered species like the California condor and the sea otter, making conservation efforts essential to maintaining biodiversity.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur's unique coastal geography influences local weather patterns, creating microclimates that foster distinct plant communities, such as the iconic redwood and cypress trees.", soundscapeID: "OceanWaves"),

    Quote(text: "Indigenous groups, including the Esselen and Ohlone tribes, have lived in harmony with the land of Big Sur for thousands of years, relying on its resources for sustenance and cultural practices.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur is rich in traditional ecological knowledge, with indigenous peoples utilizing sustainable practices to manage resources and maintain ecological balance.", soundscapeID: "OceanWaves"),
    
    Quote(text: "Efforts to preserve the ecological integrity of Big Sur are essential not only for wildlife but also for maintaining the cultural heritage of indigenous peoples in the region.", soundscapeID: "OceanWaves"),

    Quote(text: "The natural beauty and ecological significance of Big Sur continue to inspire conservation initiatives that honor the land and its original stewards.", soundscapeID: "OceanWaves"),
    
    
    Quote(text: "NASA has converted radio emissions from planets like Jupiter into sound waves, allowing us to hear the unique frequencies of these celestial bodies.", soundscapeID: "Electronic"),

    Quote(text: "The sounds of the solar wind, generated by charged particles from the sun, have been captured and translated into audio, providing insights into our solar system's dynamics.", soundscapeID: "Electronic"),

    Quote(text: "Using data from the Voyager spacecraft, NASA transformed the electromagnetic waves from the outer planets into sounds that mimic the eerie whistling of the cosmos.", soundscapeID: "Electronic"),

    Quote(text: "The intense radio emissions from Saturn's magnetosphere have been converted into sound waves, revealing the planet's unique sonic signature.", soundscapeID: "Electronic"),

    Quote(text: "NASA's Chandra X-ray Observatory has detected X-ray frequencies from distant cosmic sources, converting them into sounds that illustrate the violent processes occurring in space.", soundscapeID: "Electronic"),

    Quote(text: "The sounds produced by pulsars, rapidly rotating neutron stars emitting beams of radiation, have been translated into audio formats, allowing us to 'listen' to these cosmic lighthouses.", soundscapeID: "Electronic"),

    Quote(text: "By converting the frequencies from black holes into sound, NASA helps scientists understand the gravitational waves and phenomena associated with these mysterious entities.", soundscapeID: "Electronic"),

    Quote(text: "Data collected from the Mars rover includes atmospheric sounds converted from vibrations detected by instruments, giving us a glimpse of Martian wind and weather.", soundscapeID: "Electronic"),

    Quote(text: "NASA's imaging of cosmic background radiation has resulted in sound waves that capture the echoes of the Big Bang, offering a unique auditory experience of our universe's origins.", soundscapeID: "Electronic"),

    Quote(text: "The sounds of exoplanets, detected through variations in light and heat emissions, have been converted into audio formats, expanding our understanding of potential life beyond Earth.", soundscapeID: "Electronic"),
    
    Quote(text: "Xochimilco is home to a unique network of canals and floating gardens, known as 'chinampas,' which are an ancient Aztec agricultural technique that promotes biodiversity and sustainable farming practices.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco is designated as a UNESCO World Heritage Site due to its rich ecological diversity, including numerous endemic plant and animal species that thrive in its aquatic environments.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's canals are vital habitats for various bird species, making it an important birdwatching destination where visitors can hear the calls of species like the Mexican heron and the black-crowned night heron.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's ecosystem supports a variety of fish species, including the native axolotl, a critically endangered amphibian known for its regenerative abilities and distinctive sounds.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's lush vegetation and wetland habitats contribute to natural soundscapes, with the gentle rustling of reeds and the calls of frogs and insects creating a serene auditory experience.", soundscapeID: "Xochimilco"),

    Quote(text: "The floating gardens of Xochimilco serve as a natural filtration system, improving water quality in the canals and providing a habitat for aquatic life, while their blooming flowers attract pollinators like bees and butterflies.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's local farmers utilize sustainable farming practices in Xochimilco, which help maintain the ecological balance of the area while allowing for the production of organic crops like chilies, tomatoes, and herbs.", soundscapeID: "Xochimilco"),


    Quote(text: "The ecological significance of Xochimilco extends to its role in climate regulation, as its wetlands help store carbon and mitigate the effects of urban pollution in Mexico City.", soundscapeID: "Xochimilco"),

    Quote(text: "Efforts are underway to restore and preserve the Xochimilco ecosystem, aiming to enhance its biodiversity and promote sustainable tourism, allowing visitors to experience the harmonious sounds of nature while enjoying the area's rich cultural heritage.", soundscapeID: "Xochimilco"),
    // Add more quotes tagged with relevant soundscapeIDs
]

// Function to get random quotes based on soundscape ID
func getRandomQuote(for soundscapeID: String) -> String {
    let filteredQuotes = quotes.filter { $0.soundscapeID == soundscapeID }
    return filteredQuotes.randomElement()?.text ?? "Relax, breathe, and take life one step at a time."
}
