// Quote.swift
import Foundation

struct Quote {
    let text: String
    let soundscapeID: String
}

// List of quotes tagged by soundscape
let quotes = [
    Quote(text: "Big Sur is home to diverse ecosystems, including coastal forests, marine environments, and rugged cliffs, which support a rich variety of plant and animal life.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur serves as a critical habitat for endangered species like the California condor and the sea otter, making conservation efforts essential to maintaining biodiversity.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur's unique coastal geography influences local weather patterns, creating microclimates that foster distinct plant communities, such as the iconic redwood and cypress trees.", soundscapeID: "OceanWaves"),

    Quote(text: "Indigenous groups, including the Esselen and Ohlone tribes, have lived in harmony with the land of Big Sur for thousands of years, relying on its resources for sustenance and cultural practices.", soundscapeID: "OceanWaves"),

    Quote(text: "Big Sur is rich in traditional ecological knowledge, with indigenous peoples utilizing sustainable practices to manage resources and maintain ecological balance.", soundscapeID: "OceanWaves"),
    
    Quote(text: "Efforts to preserve the ecological integrity of Big Sur are essential not only for wildlife but also for maintaining the cultural heritage of indigenous peoples in the region.", soundscapeID: "OceanWaves"),

    Quote(text: "The natural beauty and ecological significance of Big Sur continue to inspire conservation initiatives that honor the land and its original stewards.", soundscapeID: "OceanWaves"),
    
    Quote(text: "NASA has converted radio emissions from planets like Jupiter into sound waves, allowing us to hear the unique frequencies of these celestial bodies.", soundscapeID: "Electronic"),

    Quote(text: "The sounds of the solar wind, generated by charged particles from the sun, have been captured and translated into audio, providing insights into our solar system's dynamics.", soundscapeID: "Electronic"),

    Quote(text: "Using data from the Voyager spacecraft, NASA transformed the electromagnetic waves from the outer planets into sounds that mimic the eerie whistling of the cosmos.", soundscapeID: "Electronic"),

    Quote(text: "The intense radio emissions from Saturn's magnetosphere have been converted into sound waves, revealing the planet's unique sonic signature.", soundscapeID: "Electronic"),

    Quote(text: "NASA's Chandra X-ray Observatory has detected X-ray frequencies from distant cosmic sources, converting them into sounds that illustrate the violent processes occurring in space.", soundscapeID: "Electronic"),

    Quote(text: "The sounds produced by pulsars, rapidly rotating neutron stars emitting beams of radiation, have been translated into audio formats, allowing us to 'listen' to these cosmic lighthouses.", soundscapeID: "Electronic"),

    Quote(text: "By converting the frequencies from black holes into sound, NASA helps scientists understand the gravitational waves and phenomena associated with these mysterious entities.", soundscapeID: "Electronic"),

    Quote(text: "Data collected from the Mars rover includes atmospheric sounds converted from vibrations detected by instruments, giving us a glimpse of Martian wind and weather.", soundscapeID: "Electronic"),

    Quote(text: "NASA's imaging of cosmic background radiation has resulted in sound waves that capture the echoes of the Big Bang, offering a unique auditory experience of our universe's origins.", soundscapeID: "Electronic"),

    Quote(text: "The sounds of exoplanets, detected through variations in light and heat emissions, have been converted into audio formats, expanding our understanding of potential life beyond Earth.", soundscapeID: "Electronic"),
    
    Quote(text: "Xochimilco is home to a unique network of canals and floating gardens, known as 'chinampas,' which are an ancient Aztec agricultural technique that promotes biodiversity and sustainable farming practices.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco is designated as a UNESCO World Heritage Site due to its rich ecological diversity, including numerous endemic plant and animal species that thrive in its aquatic environments.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's canals are vital habitats for various bird species, making it an important birdwatching destination where visitors can hear the calls of species like the Mexican heron and the black-crowned night heron.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's ecosystem supports a variety of fish species, including the native axolotl, a critically endangered amphibian known for its regenerative abilities and distinctive sounds.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's lush vegetation and wetland habitats contribute to natural soundscapes, with the gentle rustling of reeds and the calls of frogs and insects creating a serene auditory experience.", soundscapeID: "Xochimilco"),

    Quote(text: "The floating gardens of Xochimilco serve as a natural filtration system, improving water quality in the canals and providing a habitat for aquatic life, while their blooming flowers attract pollinators like bees and butterflies.", soundscapeID: "Xochimilco"),

    Quote(text: "Xochimilco's local farmers utilize sustainable farming practices in Xochimilco, which help maintain the ecological balance of the area while allowing for the production of organic crops like chilies, tomatoes, and herbs.", soundscapeID: "Xochimilco"),

    Quote(text: "The ecological significance of Xochimilco extends to its role in climate regulation, as its wetlands help store carbon and mitigate the effects of urban pollution in Mexico City.", soundscapeID: "Xochimilco"),

    Quote(text: "Efforts are underway to restore and preserve the Xochimilco ecosystem, aiming to enhance its biodiversity and promote sustainable tourism, allowing visitors to experience the harmonious sounds of nature while enjoying the area's rich cultural heritage.", soundscapeID: "Xochimilco"),
    
    Quote(text: "Vatnajökull Glacier is the largest glacier in Iceland and one of the largest in Europe, covering approximately 8% of the country's land area.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The glacier is a significant part of Vatnajökull National Park, which was established to protect its unique glacial landscapes and diverse ecosystems.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull is home to several active volcanoes, including Grimsvotn, which can cause dramatic glacial melting and flooding when they erupt.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The glacier is a crucial water source for Iceland, feeding numerous rivers and lakes that support both wildlife and human communities.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull Glacier's ice cap is estimated to be up to 1,000 meters thick in some areas, making it a significant contributor to sea level rise as it melts due to climate change.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The glacier's unique blue ice formations are a result of compressed snow that has turned into dense ice, creating stunning visual landscapes.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull is rich in biodiversity, supporting various flora and fauna, including Arctic foxes, reindeer, and numerous bird species during the summer months.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The surrounding region features dramatic landscapes, including glacial rivers, volcanic mountains, and geothermal areas that attract visitors from around the world.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Glacial meltwater from Vatnajökull feeds the Jökulsá á Fjöllum river, known for its unique canyons and rich ecosystem, which is vital for salmon migration.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Vatnajökull Glacier plays a significant role in Iceland's culture and history, featuring prominently in folklore and serving as a source of inspiration for artists and writers.", soundscapeID: "IcelandGlacier"),

    Quote(text: "Climate change is causing Vatnajökull Glacier to retreat at an alarming rate, with estimates suggesting it could lose up to 30% of its mass by 2100 if current warming trends continue.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The increased melting of Vatnajökull contributes to rising sea levels, which poses a threat not only to coastal communities but also to ecosystems worldwide.", soundscapeID: "IcelandGlacier"),

    Quote(text: "As temperatures rise, the glacier's melting accelerates, leading to changes in local hydrology and affecting water availability for both wildlife and human populations.", soundscapeID: "IcelandGlacier"),

    Quote(text: "The loss of Vatnajökull's ice cover is impacting the region's climate, with changes in weather patterns and increased vulnerability to natural disasters such as flooding and landslides.", soundscapeID: "IcelandGlacier"),
    
    Quote(text: "Tibetan singing bowls, also known as 'himalayan bowls,' are traditionally made from a combination of metals and are used for meditation, healing, and spiritual practices.", soundscapeID: "TibetanBowls"),

    Quote(text: "The soothing sound and vibrations produced by singing bowls can help reduce stress, promote relaxation, and facilitate deeper states of meditation.", soundscapeID: "TibetanBowls"),

    Quote(text: "Each singing bowl has its own unique frequency, which is believed to correspond to different chakras in the body, aiding in energy balancing and healing.", soundscapeID: "TibetanBowls"),

    Quote(text: "The practice of sound meditation with singing bowls involves striking or rubbing the bowl with a mallet, creating resonant tones that resonate with the listener’s energy field.", soundscapeID: "TibetanBowls"),

    Quote(text: "Singing bowls have been used for centuries in Tibetan Buddhism and other spiritual traditions as tools for enhancing meditation and mindfulness.", soundscapeID: "TibetanBowls"),

    Quote(text: "The sound of Tibetan singing bowls is said to create a calming atmosphere, allowing individuals to connect more deeply with their inner selves and the present moment.", soundscapeID: "TibetanBowls"),

    Quote(text: "Many practitioners believe that the harmonic overtones produced by singing bowls can facilitate healing on physical, emotional, and spiritual levels.", soundscapeID: "TibetanBowls"),

    Quote(text: "Sound meditation with singing bowls often includes guided visualizations and breathwork, enhancing the overall experience and promoting relaxation.", soundscapeID: "TibetanBowls"),

    Quote(text: "Singing bowls can be played alone or in group settings, creating a collective sound experience that fosters community and shared healing.", soundscapeID: "TibetanBowls"),

    Quote(text: "As awareness of sound healing grows, Tibetan singing bowls are increasingly being used in therapeutic settings, such as yoga studios and wellness centers, to support holistic healing practices.", soundscapeID: "TibetanBowls"),
    
    Quote(text: "South Dakota's diverse ecosystem includes the Great Plains, Black Hills, and Badlands, supporting a wide range of plant and animal species unique to the region.", soundscapeID: "RainStorm"),

    Quote(text: "The Black Hills are known for their rich biodiversity, with dense forests, meadows, and streams that provide habitats for species like elk, deer, and numerous bird species.", soundscapeID: "RainStorm"),

    Quote(text: "The Badlands feature dramatic rock formations and unique soil types that host rare plants and animals, including the endangered black-footed ferret.", soundscapeID: "RainStorm"),

    Quote(text: "South Dakota is home to several indigenous populations, including the Lakota Sioux, who have a deep spiritual connection to the land and its ecosystems.", soundscapeID: "RainStorm"),

    Quote(text: "The indigenous peoples of South Dakota have historically utilized the natural resources of the land for sustenance, cultural practices, and community well-being.", soundscapeID: "RainStorm"),

    Quote(text: "Cultural traditions and teachings of the Lakota Sioux emphasize the importance of living in harmony with nature, respecting all forms of life and their interconnections.", soundscapeID: "RainStorm"),

    Quote(text: "The region experiences seasonal rainstorms, which are vital for replenishing soil moisture and supporting agriculture in this predominantly grassland ecosystem.", soundscapeID: "RainStorm"),

    Quote(text: "Summer rainstorms in South Dakota can be intense, often leading to rapid changes in weather and creating opportunities for flash flooding in low-lying areas.", soundscapeID: "RainStorm"),

    Quote(text: "The state’s weather patterns are influenced by the convergence of warm and cold air masses, resulting in diverse climatic conditions and variability throughout the year.", soundscapeID: "RainStorm"),

    Quote(text: "Rainstorms contribute to the growth of native grasses and wildflowers, which are essential for the health of the local ecosystem and provide food and habitat for wildlife.", soundscapeID: "RainStorm"),
    
    Quote(text: "The Antarctic ice sheet is divided into two main parts: the East Antarctic Ice Sheet and the West Antarctic Ice Sheet, each playing a crucial role in global sea levels.", soundscapeID: "Antarctica"),

    Quote(text: "Melting glaciers in Antarctica contribute to rising sea levels, with projections indicating that significant ice loss could lead to increases of several meters over time.", soundscapeID: "Antarctica"),

    Quote(text: "The ice shelves surrounding Antarctica, such as the Ross and Filchner ice shelves, act as barriers that slow the flow of glaciers into the ocean.", soundscapeID: "Antarctica"),

    Quote(text: "Antarctica's glaciers flow into the sea at varying rates, influenced by water temperatures and ocean currents, which are changing due to climate change.", soundscapeID: "Antarctica"),

    Quote(text: "The meltwater from glaciers is a crucial component of the Southern Ocean's salinity and temperature, impacting global ocean circulation patterns.", soundscapeID: "Antarctica"),

    Quote(text: "Researchers study the movement of Antarctic glaciers to understand their response to climate change and to predict future sea level rise.", soundscapeID: "Antarctica"),

    Quote(text: "Subglacial lakes, such as Lake Vostok, lie beneath the Antarctic ice and contain unique ecosystems that have been isolated for millions of years.", soundscapeID: "Antarctica"),

    Quote(text: "The Antarctic Peninsula is experiencing rapid warming, leading to increased glacier melt and significant changes in local ecosystems and wildlife habitats.", soundscapeID: "Antarctica"),

    Quote(text: "Antarctica's ice and glaciers are vital indicators of climate change, providing valuable data for scientists studying the Earth's changing environment.", soundscapeID: "Antarctica"),
    
    Quote(text: "'In every walk with nature, one receives far more than he seeks.' - John Muir", soundscapeID: "AutumnWind"),

    Quote(text: "'The Earth has music for those who listen.' - Shakespeare", soundscapeID: "AutumnWind"),

    Quote(text: "'Look deep into nature, and then you will understand everything better.' - Albert Einstein", soundscapeID: "AutumnWind"),

    Quote(text: "'Nature does not hurry, yet everything is accomplished.' - Lao Tzu", soundscapeID: "AutumnWind"),

    Quote(text: "'The clearest way into the Universe is through a forest wilderness.' - John Muir", soundscapeID: "AutumnWind"),

    Quote(text: "'To sit in solitude, to think in solitude, is to be surrounded by the great forces of nature.' - Leonardo da Vinci", soundscapeID: "AutumnWind"),

    Quote(text: "'Nature always wears the colors of the spirit.' - Ralph Waldo Emerson", soundscapeID: "AutumnWind"),

    Quote(text: "'Adopt the pace of nature: her secret is patience.' - Ralph Waldo Emerson", soundscapeID: "AutumnWind"),

    Quote(text: "'In nature, nothing is perfect and everything is perfect.' - Alice Walker", soundscapeID: "AutumnWind"),

    Quote(text: "'The mountains are calling, and I must go.' - John Muir", soundscapeID: "AutumnWind"),

    Quote(text: "432 Hz is believed to be a natural frequency that resonates with the universe, promoting a sense of harmony and balance.", soundscapeID: "432Acoustic"),

    Quote(text: "Listening to music tuned to 432 Hz can help reduce anxiety and stress, allowing for a more relaxed state of mind.", soundscapeID: "432Acoustic"),

    Quote(text: "Many practitioners of sound meditation believe that 432 Hz frequency can enhance meditation experiences, facilitating deeper states of consciousness.", soundscapeID: "432Acoustic"),

    Quote(text: "The benefits of sound meditation include improved emotional well-being, increased focus, and a greater sense of inner peace.", soundscapeID: "432Acoustic"),

    Quote(text: "Sound meditation can stimulate the release of endorphins, the body's natural feel-good chemicals, leading to enhanced mood and relaxation.", soundscapeID: "432Acoustic"),

    Quote(text: "The shruti box is a traditional Indian instrument used to provide a continuous drone sound, creating a soothing backdrop for meditation and chanting.", soundscapeID: "432Acoustic"),

    Quote(text: "Shruti boxes are typically played by hand, producing a rich, resonant sound that helps align the mind and body during meditation practices.", soundscapeID: "432Acoustic"),

    Quote(text: "Using a shruti box in sound meditation can enhance focus and presence, making it easier to connect with one's inner self and the surrounding environment.", soundscapeID: "432Acoustic"),

    Quote(text: "The sound produced by a shruti box is often used in yoga classes and spiritual practices to deepen the meditative experience and promote relaxation.", soundscapeID: "432Acoustic"),

    Quote(text: "432 Hz sound therapy, combined with instruments like the shruti box, can help create a tranquil atmosphere conducive to healing and self-discovery.", soundscapeID: "432Acoustic"),
    
    Quote(text: "The NYC Subway is one of the largest and busiest public transportation systems in the world, with over 472 stations and more than 660 miles of track.", soundscapeID: "NYCSubway"),

    Quote(text: "Opened in 1904, the NYC Subway has been continuously expanding and now serves over 5 million passengers daily.", soundscapeID: "NYCSubway"),

    Quote(text: "The subway operates 24 hours a day, 7 days a week, making it one of the few transit systems in the world to provide continuous service.", soundscapeID: "NYCSubway"),

    Quote(text: "The iconic subway map was designed by Massimo Vignelli in 1972 and has since become a symbol of New York City’s public transit.", soundscapeID: "NYCSubway"),

    Quote(text: "The NYC Subway is divided into 26 lines, each identified by a letter or number, and covers four of the five boroughs: Manhattan, Brooklyn, Queens, and the Bronx.", soundscapeID: "NYCSubway"),

    Quote(text: "In 2020, the subway system underwent significant changes due to the COVID-19 pandemic, including reduced service and cleaning protocols to ensure passenger safety.", soundscapeID: "NYCSubway"),

    Quote(text: "The NYC Subway is known for its art installations, with numerous stations featuring murals, mosaics, and sculptures from various artists.", soundscapeID: "NYCSubway"),

    Quote(text: "With over 100 years of history, the NYC Subway has become an integral part of the city's identity and culture, influencing everything from music to film.", soundscapeID: "NYCSubway"),

    Quote(text: "The subway’s complex tunnel system includes unique features such as abandoned stations, secret passageways, and even ghost trains.", soundscapeID: "NYCSubway"),

    Quote(text: "In addition to providing transportation, the NYC Subway also serves as a venue for street performers and musicians, contributing to the city’s vibrant cultural scene.", soundscapeID: "NYCSubway"),
    
    Quote(text: "Barcelona is renowned for its unique architecture, with famous works by Antoni Gaudí, including the Sagrada Família and Park Güell, attracting millions of visitors each year.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "The city’s Gothic Quarter, known as Barri Gòtic, features narrow medieval streets, hidden squares, and historic buildings dating back to the Roman period.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "Barcelona’s vibrant street life includes bustling markets like La Boqueria, where locals and tourists alike can enjoy fresh produce and traditional Catalan cuisine.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "The city is famous for its beaches, with over 4.5 kilometers of coastline that offer a mix of relaxation, water sports, and lively beach bars.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "Barcelona is also known for its rich cultural scene, with numerous festivals, concerts, and art exhibitions held throughout the year.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "The public transportation system in Barcelona includes an extensive network of buses, trams, and a metro system that makes exploring the city convenient.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "Barcelona's streets are adorned with modernist architecture, and the city's urban planning emphasizes pedestrian-friendly spaces and green areas.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "The city hosts numerous parks, such as Montjuïc and Ciutadella Park, providing green spaces for relaxation and recreation amidst urban life.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "Barcelona is a UNESCO World Heritage Site, recognized for its architectural and artistic heritage, with several Gaudí buildings listed as cultural landmarks.", soundscapeID: "BarcelonaStreet"),

    Quote(text: "The lively street culture of Barcelona includes street performers, artists, and open-air markets that reflect the city's dynamic and diverse community.", soundscapeID: "BarcelonaStreet"),
    
    Quote(text: "Mushrooms are a type of fungi that play a crucial role in ecosystems as decomposers, breaking down organic matter and recycling nutrients back into the soil.", soundscapeID: "Mushroom"),

    Quote(text: "Many mushrooms possess unique medicinal properties, with species like reishi and lion's mane being used in traditional medicine to boost immune function and enhance cognitive health.", soundscapeID: "Mushroom"),

    Quote(text: "Mushrooms can produce a wide range of bioactive compounds, including polysaccharides, terpenes, and phenolic compounds, which have potential health benefits.", soundscapeID: "Mushroom"),

    Quote(text: "Some mushrooms, such as the famous psilocybin mushrooms, are known for their psychoactive properties and are being studied for their potential in mental health treatments.", soundscapeID: "Mushroom"),

    Quote(text: "Edible mushrooms like shiitake, portobello, and oyster mushrooms are not only delicious but also rich in essential nutrients, including vitamins, minerals, and antioxidants.", soundscapeID: "Mushroom"),

    Quote(text: "Mushrooms have a unique ability to absorb heavy metals and toxins from the soil, making them potential candidates for bioremediation efforts in polluted environments.", soundscapeID: "Mushroom"),

    Quote(text: "Certain fungi can form symbiotic relationships with plants through mycorrhizal networks, enhancing nutrient uptake and improving plant health and resilience.", soundscapeID: "Mushroom"),

    Quote(text: "Mushrooms can be found in a variety of habitats, from forests to grasslands, and their diverse forms range from tiny fairy ring mushrooms to large polypores.", soundscapeID: "Mushroom"),

    Quote(text: "Some mushrooms exhibit bioluminescence, producing light in the dark, which may attract insects that help disperse their spores.", soundscapeID: "Mushroom"),

    Quote(text: "The study of mushrooms, known as mycology, is a growing field that explores their ecological roles, potential health benefits, and applications in sustainable practices.", soundscapeID: "Mushroom"),
    
    Quote(text: "The Bonneville Salt Flats are a mesmerizing expanse of white, where the earth and sky meet in a breathtaking horizon, creating a landscape like no other.", soundscapeID: "Bonneville"),

    Quote(text: "This unique location has become an iconic site for land speed racing, attracting thrill-seekers and record-breakers from around the world.", soundscapeID: "Bonneville"),

    Quote(text: "The vast, flat surface of the salt flats is a testament to nature's artistry, formed over thousands of years through evaporation and geological processes.", soundscapeID: "Bonneville"),

    Quote(text: "Walking on the Bonneville Salt Flats feels like stepping into a dream, where the reflective surface creates an illusion of endless space.", soundscapeID: "Bonneville"),

    Quote(text: "The salt flats are not just a striking landscape; they also serve as an important habitat for wildlife, including migratory birds and unique salt-tolerant plants.", soundscapeID: "Bonneville"),

    Quote(text: "Photographers flock to the Bonneville Salt Flats for their stunning sunrises and sunsets, capturing the vibrant colors that dance across the horizon.", soundscapeID: "Bonneville"),

    Quote(text: "The Bonneville Salt Flats have a rich history, from ancient civilizations that utilized the area to the modern-day events that celebrate speed and innovation.", soundscapeID: "Bonneville"),

    Quote(text: "As the sun beats down on the salt crust, the landscape shimmers with heat, creating a surreal and captivating atmosphere for visitors.", soundscapeID: "Bonneville"),

    Quote(text: "The Bonneville Salt Flats remind us of the power of nature and the beauty that can be found in even the most extreme environments.", soundscapeID: "Bonneville"),

    Quote(text: "Visiting the Bonneville Salt Flats is an experience that transcends mere sightseeing; it’s a journey into a world where nature and human ambition collide.", soundscapeID: "Bonneville"),
    
    Quote(text: "The Rocky Mountains stretch over 3,000 miles from Canada to New Mexico, making them one of the longest mountain ranges in North America.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "Home to numerous national parks, including Rocky Mountain National Park and Glacier National Park, the Rockies offer stunning landscapes and diverse ecosystems.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "The Rockies are known for their rugged terrain, including jagged peaks, deep valleys, and crystal-clear lakes, attracting outdoor enthusiasts year-round.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "Wildlife in the Rocky Mountains includes species such as elk, bighorn sheep, mountain goats, and black bears, making it a popular destination for wildlife watching.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "The Rocky Mountains are rich in geological history, with formations dating back over 300 million years, showcasing a variety of rock types and minerals.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "The area is renowned for its outdoor recreational opportunities, including hiking, skiing, snowboarding, rock climbing, and mountain biking.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "The stunning vistas of the Rockies have inspired countless artists, musicians, and writers, contributing to the cultural heritage of the region.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "Indigenous peoples, such as the Ute and Shoshone tribes, have historically inhabited the Rocky Mountains, relying on its resources for sustenance and cultural practices.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "The Rockies play a crucial role in the water supply for the western United States, with many rivers originating in the mountain range.", soundscapeID: "RockyMountainMusic"),

    Quote(text: "The Rocky Mountains offer a unique soundscape, from the rustling of pine trees to the sounds of rushing rivers, creating a peaceful environment for reflection and meditation.", soundscapeID: "RockyMountainMusic"),
    
    Quote(text: "The 34-inch symphonic gong produces deep, resonant tones that are known for their calming and grounding effects during meditation and sound therapy.", soundscapeID: "SymphonicGong"),

    Quote(text: "Gongs have been used for centuries in various cultures for healing, meditation, and ceremonial purposes, symbolizing the unity of mind and body.", soundscapeID: "SymphonicGong"),

    Quote(text: "The rich harmonic overtones created by a symphonic gong can help induce deep states of relaxation and facilitate a meditative experience.", soundscapeID: "SymphonicGong"),

    Quote(text: "Playing a symphonic gong can stimulate the body's energy centers, or chakras, promoting balance and well-being.", soundscapeID: "SymphonicGong"),

    Quote(text: "The sound waves produced by the gong can help to reduce stress and anxiety, encouraging a sense of peace and tranquility.", soundscapeID: "SymphonicGong"),

    Quote(text: "In sound meditation sessions, the 34-inch symphonic gong is often used as a focal point, guiding participants into a state of mindfulness and presence.", soundscapeID: "SymphonicGong"),

    Quote(text: "The gong's vibrations can penetrate the body, helping to release tension and blockages stored in the physical and energetic systems.", soundscapeID: "SymphonicGong"),

    Quote(text: "Many practitioners find that the sound of the gong helps to quiet the mind, allowing for a deeper connection to one's inner self during meditation.", soundscapeID: "SymphonicGong"),

    Quote(text: "Symphonic gongs are often featured in group sound healing sessions, creating a collective experience that enhances the healing process for participants.", soundscapeID: "SymphonicGong"),

    Quote(text: "The 34-inch symphonic gong is not only an instrument but also a powerful tool for transformation, promoting emotional release and spiritual growth.", soundscapeID: "SymphonicGong"),
    
    Quote(text: "New Delhi is home to vibrant bazaars, such as Chandni Chowk, which is one of the oldest and busiest markets in the city, offering a variety of goods and street food.", soundscapeID: "Bazaar"),

    Quote(text: "The bazaars in New Delhi are renowned for their bustling atmosphere, colorful stalls, and the rich aromas of spices, sweets, and local cuisine.", soundscapeID: "Bazaar"),

    Quote(text: "Dilli Haat is a unique open-air market that showcases handicrafts and cuisines from different states of India, promoting cultural diversity and local artisans.", soundscapeID: "Bazaar"),

    Quote(text: "The bazaars often feature a mix of traditional and modern shops, selling everything from textiles and jewelry to electronics and souvenirs.", soundscapeID: "Bazaar"),

    Quote(text: "Khan Market is one of the most upscale bazaars in New Delhi, known for its high-end boutiques, cafes, and specialty stores.", soundscapeID: "Bazaar"),

    Quote(text: "Street vendors in New Delhi's bazaars offer a wide range of delicious snacks, including chaat, parathas, and sweets like jalebi and gulab jamun.", soundscapeID: "Bazaar"),

    Quote(text: "The bazaars are not only shopping destinations but also cultural hubs, where visitors can experience local traditions, festivals, and community events.", soundscapeID: "Bazaar"),

    Quote(text: "Shopping in New Delhi's bazaars often involves haggling, making it an interactive experience that reflects the local culture and commerce.", soundscapeID: "Bazaar"),

    Quote(text: "The bazaars are accessible by various modes of transportation, including the Delhi Metro, making them popular destinations for both locals and tourists.", soundscapeID: "Bazaar"),

    Quote(text: "Exploring the bazaars of New Delhi offers a glimpse into the city's rich heritage, vibrant lifestyle, and the warmth of its people.", soundscapeID: "Bazaar"),
    
    Quote(text: "Tikal Temple, part of the ancient Mayan city of Tikal, is a UNESCO World Heritage Site and one of the most significant archaeological sites in Central America.", soundscapeID: "TikalTemple"),

    Quote(text: "The temple complex dates back to around 200-900 AD and features impressive structures, including temples, plazas, and ceremonial platforms.", soundscapeID: "TikalTemple"),

    Quote(text: "Tikal Temple I, also known as Temple of the Great Jaguar, stands 47 meters tall and served as a funerary temple for the Mayan ruler Jasaw Chan K'awil.", soundscapeID: "TikalTemple"),

    Quote(text: "The site was once a major political, economic, and cultural center for the Mayan civilization, showcasing advanced architectural and engineering skills.", soundscapeID: "TikalTemple"),

    Quote(text: "Tikal is surrounded by lush rainforest, home to diverse wildlife, including howler monkeys, toucans, and jaguars, which contribute to the area's rich biodiversity.", soundscapeID: "TikalTemple"),

    Quote(text: "The soundscape of Tikal is characterized by the calls of exotic birds, the rustling of leaves, and the distant sounds of wildlife, creating a serene environment.", soundscapeID: "TikalTemple"),

    Quote(text: "Visitors to Tikal can experience the blend of ancient history and nature, as the ruins are often enveloped by the sounds of the jungle.", soundscapeID: "TikalTemple"),

    Quote(text: "Tikal Temple's significance extends beyond its architecture; it provides valuable insights into Mayan cosmology, religion, and societal organization.", soundscapeID: "TikalTemple"),

    Quote(text: "The site is a popular destination for tourists and archaeologists alike, offering guided tours that highlight its historical and ecological importance.", soundscapeID: "TikalTemple"),

    Quote(text: "Preserving Tikal Temple and its surrounding ecosystem is crucial for maintaining the cultural heritage and wildlife of Guatemala.", soundscapeID: "TikalTemple"),
    
    Quote(text: "Akagera National Park is Rwanda's largest protected wetland and savannah park, covering approximately 1,120 square kilometers.", soundscapeID: "Rwanda"),

    Quote(text: "The park is home to a diverse range of wildlife, including elephants, giraffes, zebras, and various species of antelope, making it a prime destination for wildlife enthusiasts.", soundscapeID: "Rwanda"),

    Quote(text: "Akagera National Park is known for its rich birdlife, with over 500 species recorded, including the endangered shoe bill stork and numerous waterfowl.", soundscapeID: "Rwanda"),

    Quote(text: "The park features a unique ecosystem that includes lakes, wetlands, grasslands, and woodlands, providing habitats for various flora and fauna.", soundscapeID: "Rwanda"),

    Quote(text: "Akagera was established in 1934 and has undergone significant restoration efforts in recent years, including reintroducing large mammals such as lions and rhinos.", soundscapeID: "Rwanda"),

    Quote(text: "The park offers various activities, including game drives, boat trips on Lake Akagera, and guided nature walks, allowing visitors to experience its natural beauty.", soundscapeID: "Rwanda"),

    Quote(text: "Visitors to Akagera National Park can enjoy breathtaking landscapes, including rolling hills, savannah plains, and stunning views of the park's lakes.", soundscapeID: "Rwanda"),

    Quote(text: "Conservation efforts in Akagera focus on sustainable tourism practices that benefit local communities while preserving the park's biodiversity.", soundscapeID: "Rwanda"),

    Quote(text: "The soundscape of Akagera is characterized by the calls of birds, the rustling of grass, and the distant sounds of wildlife, creating a tranquil atmosphere.", soundscapeID: "Rwanda"),

    Quote(text: "Akagera National Park plays a crucial role in protecting Rwanda's natural heritage and contributes to the country's overall conservation and ecotourism efforts.", soundscapeID: "Rwanda"),



    // Add more quotes tagged with relevant soundscapeIDs
]

// Function to get random quotes based on soundscape ID
func getRandomQuote(for soundscapeID: String) -> String {
    let filteredQuotes = quotes.filter { $0.soundscapeID == soundscapeID }
    return filteredQuotes.randomElement()?.text ?? "Relax, breathe, and take life one step at a time."
}
